name: SkyHigh
description: After a certain period of time, all players below y 100 will take half a heart of damage every 30 seconds.
version: 1.0.0
author: Caleb Bassham
depend: [ScenarioManager]
main: me.calebbassham.skyhigh.SkyHighPlugin